name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub.

  - type: input
    id: Code
    attributes:
      label: Custom Code
      description: Have I written custom code (as opposed to using a stock example script provided in TensorFlow)
      placeholder: yes/no
    validations:
      required: false
  - type: input
    id: OS
    attributes:
      label: OS Platform and Distribution
      description: 
      placeholder: e.g., Linux Ubuntu 16.04
    validations:
      required: false
  - type: input
    id: Mobile
    attributes:
      label: Mobile device
      description: 
      placeholder: e.g., Linux Ubuntu 16.04
    validations:
      required: false
  - type: input
    id: Python
    attributes:
      label: Python version
      description: 
      placeholder: e.g., 3.9
    validations:
      required: false
  - type: input
    id: Bazel
    attributes:
      label: Bazel version
      description: if compiling from source
      placeholder: 
    validations:
      required: false
  - type: input
    id: Compiler
    attributes:
      label: GCC/Compiler version
      description: if compiling from source
      placeholder: 
    validations:
      required: false
  - type: input
    id: Cuda
    attributes:
      label: CUDA/cuDNN version
      description:
      placeholder: 
    validations:
      required: false
  - type: input
    id: Gpu
    attributes:
      label: GPU model and memory
      description: if compiling from source
      placeholder: 
    validations:
      required: false
  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Tensorflow installed from
      options:
        - source
        - binary
    validations:
      required: true
  - type: dropdown
    id: tfversion
    attributes:
      label: Tensorflow Version
      multiple: true
      options:
        - 2.8
        - 2.7
        - 2.6
        - 2.5
  - type: textarea
    id: what-happened
    attributes:
      label: Current Behaviour?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
